defaults:
  - _self_
  - payloads: cargo

run_name: ${optimiser}_${scorer_method}
hydra:
  run:
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}_${run_name}

url: http://127.0.0.1:7860
device: cpu

wildcards_dir: path/to/wildcards/folder
scorer_model_dir: path/to/scorer/models/folder

model_a: path/to/model_a/file
model_b: path/to/model_b/file
model_c: path/to/model_c/file # optional
model_d: path/to/model_d/file # optional
model_e: path/to/model_e/file # optional
skip_position_ids: 0
cosine_mode: False  # Experiemental Merge mode, only set to true when used with add_difference or weighted sum
merge_mode: weighted_sum  # weighted_sum (default), add_difference, weighted_add_difference,  sum_twice, triple_sum, weighted_double_difference

enable_fix_blocks: False
fix_block_values:
  - block_0: 0.9
  - block_1: 0.1

enable_block_groups: False
block_groups:
  - [block_0, block_1]
  - [block_2, block_3]

optimiser: bayes # tpe
bounds_transformer: False
batch_size: 1
init_points: 1
n_iters: 1

save_imgs: False

scorer_method: chad # laion, aes, cafe_aesthetic, cafe_style, cafe_waifu
scorer_model_name: sac+logos+ava1-l14-linearMSE.pth # ava+logos-l14-linearMSE.pth, ava+logos-l14-reluMSE.pth

save_best: False
best_format: safetensors # ckpt
best_precision: 16 # 32

draw_unet_weights: False
draw_unet_base_alpha: False
